#Automaticaly Generated by sb-env.
#For more info, see fedx-sudo.github.io/SpaceBusOS-wiki
with import <nixpkgs> {};

stdenv.mkDerivation {
  name = "SBOS-install";
  buildInputs = [
    
  ];
  src = /home/fedx/Code/SpaceBusOS;
  installPhase = ''
    mkdir -p $out/bin
    cp install.sh $out/bin
    cp laptop-install.sh $out/bin
    
  '';
}

