title = "SpaceBusOS Garuda dr460nized edition"

[bedrock-config]

enable = true

url = https://raw.githubusercontent.com/FedX-sudo/SpaceBusOS/main/Editions/dr460nized/config/bedrock.conf

[brl-fetch]

enabled = true

distros = ["-n garuda arch"]

[additional-packages]

enabled = true

garuda:pacman = ["kate", "konsole", "garuda-settings-manager-git", "dolphin", "
