title = "SpaceBusOS Desktop Edition Config File"

[bedrock-config]

enable = true

url = https://raw.githubusercontent.com/FedX-sudo/SpaceBusOS/main/Editions/Desktop/config/bedrock.conf

[packages]

enabled = true

conflicts = ["KDE", "Plasma"]

[required]
	arch:pacman = ["plasma-meta"]
	nix = []


[optional]
	apk = []
	nix = []
	pacman = []

[additinal-config]

enabled = true

[plasma]
	url = "https://raw.githubusercontent.com/FedX-sudo/SpaceBusOS/main/Editions/Desktop/config/plasmarc"

	path = "~/.config/plasmarc"

[konsole]
    url = "https://raw.githubusercontent.com/FedX-sudo/SpaceBusOS/main/Editions/Desktop/config/plasmarc"

	path = "~/.config/plasmarc"

